### ISSUE TITLE
please add browser sync

### ISSUE THREAD

**Issue by weilinzung** [solarsailer/jekyll-boilerplate#1]
the build is not looking for the file changes with browser sync, please add this feature.
And when run `yarn run start`, not auto open the browser page?

thanks!

**Comment by solarsailer** [comment]
Hello,

It does use BrowserSync (but not for HTML or posts changes). If you tweak a CSS file, for example, it will automatically refresh the page.

If you want to open a browser after `yarn run start`, change this line to `true`: https://github.com/solarsailer/jekyll-boilerplate/blob/master/webpack.config.js#L125

Cheers.

**Comment by weilinzung** [comment]
thanks, would it possible watch all the html changes? and how about if I want to install other JS plugins from NPM? if I just run `yarn add plugin-name`, would the template automally included the JS & CSS?

**Comment by solarsailer** [comment]
> thanks, would it possible watch all the html changes?

You could, this would just need some changes in the webpack config (I had a good reason to not do it but I can't remember it ;p).

> if I just run yarn add plugin-name, would the template automally included the JS & CSS?

Yes. However, you would need to `require` it in a .js file, or `import` it in a .scss file. See `normalize.css` for an example.
